project:
  type: website
  output-dir: docs

website:
  title: "STA 9750 Submission Material"
  description:
    Course Projects for STA 9750 at Baruch College
  site-url: "https://ShahriaAhmed.github.io/STA9750-2025-FALL/"
  navbar:
    #background: primary
    search: false
    collapse-below: xl
    right:
      - text: "Home"
        href: index.qmd
      - text: "Other Projects"
        href: projects.qmd
      - text: "Project #1"
        href: mp01.qmd
      - text: "Project #2"
        href: mp02.qmd
      - text: "Project #3"
        href: mp03.qmd
      - text: "Project #4"
        href: mp04.qmd
      - text: "Final Project"
        href: finalproject.qmd
      - icon: github
        href: https://github.com/ShahriaAhmed/STA9750-2025-FALL
format:
  html:
    theme: default
    toc: false
    css: styles.css
    code-fold: true
    code-summary: "Show code"
    
editor:
  mode: source